#set(BASE_NAME arm-none-eabi)
#
#SET(CMAKE_C_COMPILER    ${BASE_NAME}-gcc      )
#SET(CMAKE_CXX_COMPILER  ${BASE_NAME}-g++      )
#SET(CMAKE_LINKER        ${BASE_NAME}-ld       )
#SET(CMAKE_ASM_COMPILER  ${BASE_NAME}-as       )
#SET(CMAKE_OBJCOPY       ${BASE_NAME}-objcopy  )
#SET(CMAKE_STRIP         ${BASE_NAME}-strip    )
#SET(CMAKE_CPP           ${BASE_NAME}-cpp      )
#
#set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
#set(CMAKE_SYSTEM_NAME          Generic)
#set(CMAKE_HOST_SYSTEM_NAME     Windows)
#set(CMAKE_SYSTEM_PROCESSOR     ARM2)
#set(CMAKE_EXECUTABLE_SUFFIX    ".elf")

set(BASE_NAME arm-none-eabi)

SET(CMAKE_C_COMPILER    ${BASE_NAME}-gcc               CACHE STRING "COMP")
SET(CMAKE_CXX_COMPILER  ${BASE_NAME}-g++               CACHE STRING "COMP")
SET(CMAKE_LINKER        ${BASE_NAME}-ld                CACHE STRING "COMP")
#SET(CMAKE_ASM_COMPILER  ${BASE_NAME}-as               CACHE STRING "COMP")
#SET(CMAKE_ASM_COMPILER "${BASE_NAME}-gcc -x assembler" CACHE STRING "COMP")
SET(CMAKE_ASM_COMPILER "${BASE_NAME}-gcc"               CACHE STRING "COMP")
SET(CMAKE_OBJCOPY       ${BASE_NAME}-objcopy           CACHE STRING "COMP")
SET(CMAKE_STRIP         ${BASE_NAME}-strip             CACHE STRING "COMP")
SET(CMAKE_CPP           ${BASE_NAME}-cpp               CACHE STRING "COMP")
SET(CMAKE_CC            ${BASE_NAME}-cc                CACHE STRING "COMP")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY       CACHE STRING "COMP")
set(CMAKE_SYSTEM_NAME          Generic                 CACHE STRING "COMP")
#set(CMAKE_HOST_SYSTEM_NAME     Windows                CACHE STRING "COMP")
set(CMAKE_HOST_SYSTEM_NAME     Linux                   CACHE STRING "COMP")
set(CMAKE_SYSTEM_PROCESSOR     ARM2                    CACHE STRING "COMP")
set(CMAKE_EXECUTABLE_SUFFIX    ".elf"                  CACHE STRING "COMP")